# Generated by Django 5.2 on 2026-05-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text='Ingrese su correo electrónico ', max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('tipo_documento', models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cédula de Ciudadanía'), ('PASSPORT', 'Pasaporte'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
